version: '3'

services:

  express_app:
    container_name: express_app
    build:
      context: ./
      dockerfile: Dockerfile 
    depends_on:
      - mongo
    environment:
      PORT: 5000
    ports:
      - 3030:5000
    restart: always
    command: npm run dev
    volumes:
      - ./:/app
      - /app/node_modules

  mongo:
    container_name: mongo
    image: mongo:latest
    expose:
      - 27017
    ports:
      - 27017:27017
    volumes:
      - /data/db
